- name: Manage IAM users and groups
  hosts: localhost
  vars_files:
    - 'vars/groups.yml'
    - 'vars/users.yml'
  vars:
    pass: "{{ password }}"
  gather_facts: False
  tasks:
    - name: Statefully manage IAM groups
      iam:
        iam_type: group
        name: "{{ item }}"
        state: present
      loop: "{{ groups }}"
      register: new_groups

    - name:
      iam:
        iam_type: user
        name: "{{ item.0.name }}"
        state: present
        groups: "{{ item.1 }}"
        password: "{{ pass }}"
      loop: "{{ users|subelements('groups') }}"
